# Generated by Django 2.2 on 2022-05-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_make_fields_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_at__date', 'start_at__time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
